### ISSUE TITLE
 Radar type undefined

### ISSUE THREAD

**Issue by abanger** [CyanideCN/PyCINRAD#42]
Traceback (most recent call last):
  File "qzppi.py", line 45, in <module>
    f = CinradReader(sa_radar_file[nFiles]) #老版本数据
  File "C:\Anaconda3\lib\site-packages\cinrad\io\level2.py", line 124, in __init__
    self.code, radartype = _detect_radartype(f, filename, type_assert=radar_type)
  File "C:\Anaconda3\lib\site-packages\cinrad\io\level2.py", line 71, in _detect_radartype
    raise RadarDecodeError('Radar type undefined')
cinrad.error.RadarDecodeError: Radar type undefined

**Comment by abanger** [comment]
> 你是读的哪个雷达的数据？
发现是程序是以文件名来区分不同站。文件名加上站名就可以了。
